spring.application.name=demo

# Supabase 連線資訊
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.bwumuyiczuevwknjikdq
spring.datasource.password=XYZwhvwN6Yk0pJed
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect